version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m server
    stdin_open: true
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    #   links:
    depends_on:
      - db

  db:
    image: "keinos/sqlite3:latest"